# @package _group_
hydra:
  run:
    dir: .

common:
  log_format: tqdm
  log_interval: 5
  wandb_project: forvis-organ

checkpoint:
  save_dir: outputs/organ/test01

task:
  _name: organ
  organ_dict: data-bin/organ/organ_dict.json
  trian_tsv: data-bin/organ/all_organs.tsv
  val_size: 0.2

dataset:
  num_workers: 4
  batch_size: 16

criterion:
  _name: organ-ce-multiclass

optimization:
  max_epoch: 20
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: fixed

model:
  _name: resnet18-512
  base_layers: 6

distributed_training:
  distributed_world_size: 1
  ddp_backend: no_c10d
